# Generated by Django 5.2 on 2025-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooklyApp', '0002_alter_book_options_remove_book_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Uncategorized', max_length=50, null=True),
        ),
    ]
