# Generated by Django 5.2 on 2025-05-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooklyApp', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
